{% set name = "distgen" %}
{% set version = "2.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ColwynGulliford/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: d3a26f321f9f42d4392d51fc72a2d4078edcde888b1869775efb2c578e86346c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - h5py
    - matplotlib-base
    - numpy
    - pint
    - scipy
    - openpmd-beamphysics
    - pyyaml
    - lume-base
    - pydicom

test:
  requires:
    - python {{ python_min }}
  imports:
    - distgen

about:
  home: https://github.com/ColwynGulliford/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Particle distribution generator
  description: |
    Particle distribution generator

extra:
  recipe-maintainers:
    - ColwynGulliford
